import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'Data Fetching Strategies – Next.js',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang='de'>
      <body>{children}</body>
    </html>
  );
}
